export interface Feed {
  id: string;
  name: string;
  shortName: string;
  agency: string;
  description: string;
  rssUrl: string;
  website: string;
  department: string;
  category: string;
  subCategory: string;
  contentType: string;
  updateFrequency: string;
  status: "working" | "blocked" | "unverified";
  tags: string[];
}

export const feeds: Feed[] = [
  {id:"feed-022",name:"NIST News",shortName:"NIST News",agency:"National Institute of Standards",description:"Technology Standards",rssUrl:"https://www.nist.gov/news-events/news/rss.xml",website:"https://www.nist.gov",department:"",category:"Commerce & Trade",subCategory:"technology-standards",contentType:"Technology Standards",updateFrequency:"",status:"working" as const,tags:["technology-standards"]},
  {id:"feed-034",name:"GovInfo - Bills",shortName:"GovInfo - Bills",agency:"GovInfo",description:"congress",rssUrl:"https://www.govinfo.gov/rss/bills.xml",website:"https://www.govinfo.gov",department:"",category:"Congress & Legislation",subCategory:"congress",contentType:"congress",updateFrequency:"",status:"working" as const,tags:["congress"]},
  {id:"feed-038",name:"GovInfo - Congressional Record",shortName:"GovInfo - Congressional Record",agency:"GovInfo",description:"congress",rssUrl:"https://www.govinfo.gov/rss/crec.xml",website:"https://www.govinfo.gov",department:"",category:"Congress & Legislation",subCategory:"congress",contentType:"congress",updateFrequency:"",status:"working" as const,tags:["congress"]},
  {id:"feed-039",name:"GovInfo - Congressional Record Index",shortName:"GovInfo - Congressional Record Index",agency:"GovInfo",description:"congress",rssUrl:"https://www.govinfo.gov/rss/cri.xml",website:"https://www.govinfo.gov",department:"",category:"Congress & Legislation",subCategory:"congress",contentType:"congress",updateFrequency:"",status:"working" as const,tags:["congress"]},
  {id:"feed-049",name:"GovInfo - Public and Private Laws",shortName:"GovInfo - Public and Private Laws",agency:"GovInfo",description:"congress",rssUrl:"https://www.govinfo.gov/rss/plaw.xml",website:"https://www.govinfo.gov",department:"",category:"Congress & Legislation",subCategory:"congress",contentType:"congress",updateFrequency:"",status:"working" as const,tags:["congress"]},
  {id:"feed-059",name:"GovInfo Congressional Documents",shortName:"GovInfo Congressional Documents",agency:"US GPO / GovInfo",description:"Messages from the President, executive branch reports, and miscellaneous statutory filings.",rssUrl:"https://www.govinfo.gov/rss/cdoc.xml",website:"https://www.govinfo.gov",department:"",category:"Congress & Legislation",subCategory:"Congress & Legislation",contentType:"Messages from the President, executive branch reports, and miscellaneous statutory filings.",updateFrequency:"",status:"working" as const,tags:["congress & legislation"]},
  {id:"feed-060",name:"GovInfo Congressional Hearings",shortName:"GovInfo Congressional Hearings",agency:"US GPO / GovInfo",description:"Transcripts and written testimony of public and oversight hearings of House and Senate panels.",rssUrl:"https://www.govinfo.gov/rss/chrg.xml",website:"https://www.govinfo.gov",department:"",category:"Congress & Legislation",subCategory:"Congress & Legislation",contentType:"Transcripts and written testimony of public and oversight hearings of House and Senate panels.",updateFrequency:"",status:"working" as const,tags:["congress & legislation"]},
  {id:"feed-061",name:"GovInfo Congressional Reports",shortName:"GovInfo Congressional Reports",agency:"US GPO / GovInfo",description:"Senate and House committee recommendations, program evaluations, and fiscal analyses.",rssUrl:"https://www.govinfo.gov/rss/crpt.xml",website:"https://www.govinfo.gov",department:"",category:"Congress & Legislation",subCategory:"Congress & Legislation",contentType:"Senate and House committee recommendations, program evaluations, and fiscal analyses.",updateFrequency:"",status:"working" as const,tags:["congress & legislation"]},
  {id:"feed-064",name:"1st Circuit - Opinions",shortName:"1st Circuit - Opinions",agency:"1st Circuit",description:"courts",rssUrl:"https://www.ca1.uscourts.gov/opn/feed",website:"https://www.ca1.uscourts.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-065",name:"1st Circuit - Oral Arguments",shortName:"1st Circuit - Oral Arguments",agency:"1st Circuit",description:"courts",rssUrl:"https://www.ca1.uscourts.gov/doarrss/feed",website:"https://www.ca1.uscourts.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-078",name:"GovInfo - 10th Circuit",shortName:"GovInfo - 10th Circuit",agency:"GovInfo",description:"courts",rssUrl:"https://www.govinfo.gov/rss/uscourts-ca10.xml",website:"https://www.govinfo.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-079",name:"GovInfo - 11th Circuit",shortName:"GovInfo - 11th Circuit",agency:"GovInfo",description:"courts",rssUrl:"https://www.govinfo.gov/rss/uscourts-ca11.xml",website:"https://www.govinfo.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-080",name:"GovInfo - 1st Circuit",shortName:"GovInfo - 1st Circuit",agency:"GovInfo",description:"courts",rssUrl:"https://www.govinfo.gov/rss/uscourts-ca1.xml",website:"https://www.govinfo.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-082",name:"GovInfo - 3rd Circuit",shortName:"GovInfo - 3rd Circuit",agency:"GovInfo",description:"courts",rssUrl:"https://www.govinfo.gov/rss/uscourts-ca3.xml",website:"https://www.govinfo.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-083",name:"GovInfo - 4th Circuit",shortName:"GovInfo - 4th Circuit",agency:"GovInfo",description:"courts",rssUrl:"https://www.govinfo.gov/rss/uscourts-ca4.xml",website:"https://www.govinfo.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-084",name:"GovInfo - 5th Circuit",shortName:"GovInfo - 5th Circuit",agency:"GovInfo",description:"courts",rssUrl:"https://www.govinfo.gov/rss/uscourts-ca5.xml",website:"https://www.govinfo.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-085",name:"GovInfo - 6th Circuit",shortName:"GovInfo - 6th Circuit",agency:"GovInfo",description:"courts",rssUrl:"https://www.govinfo.gov/rss/uscourts-ca6.xml",website:"https://www.govinfo.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-086",name:"GovInfo - 7th Circuit",shortName:"GovInfo - 7th Circuit",agency:"GovInfo",description:"courts",rssUrl:"https://www.govinfo.gov/rss/uscourts-ca7.xml",website:"https://www.govinfo.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-087",name:"GovInfo - 8th Circuit",shortName:"GovInfo - 8th Circuit",agency:"GovInfo",description:"courts",rssUrl:"https://www.govinfo.gov/rss/uscourts-ca8.xml",website:"https://www.govinfo.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-088",name:"GovInfo - 9th Circuit",shortName:"GovInfo - 9th Circuit",agency:"GovInfo",description:"courts",rssUrl:"https://www.govinfo.gov/rss/uscourts-ca9.xml",website:"https://www.govinfo.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-091",name:"GovInfo - DC Circuit",shortName:"GovInfo - DC Circuit",agency:"GovInfo",description:"courts",rssUrl:"https://www.govinfo.gov/rss/uscourts-cadc.xml",website:"https://www.govinfo.gov",department:"",category:"Courts & Judiciary",subCategory:"courts",contentType:"courts",updateFrequency:"",status:"working" as const,tags:["courts"]},
  {id:"feed-119",name:"DoD - Advisories",shortName:"DoD - Advisories",agency:"DoD",description:"defense",rssUrl:"https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?max=10&ContentType=2&Site=945",website:"https://www.defense.gov",department:"",category:"Defense & Security",subCategory:"defense",contentType:"defense",updateFrequency:"",status:"working" as const,tags:["defense"]},
  {id:"feed-120",name:"DoD - Contracts",shortName:"DoD - Contracts",agency:"DoD",description:"defense",rssUrl:"https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=400&Site=945&max=10",website:"https://www.defense.gov",department:"",category:"Defense & Security",subCategory:"defense",contentType:"defense",updateFrequency:"",status:"working" as const,tags:["defense"]},
  {id:"feed-122",name:"DoD - News",shortName:"DoD - News",agency:"DoD",description:"defense",rssUrl:"https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?max=10&ContentType=1&Site=945",website:"https://www.defense.gov",department:"",category:"Defense & Security",subCategory:"defense",contentType:"defense",updateFrequency:"",status:"working" as const,tags:["defense"]},
  {id:"feed-123",name:"DoD - Releases",shortName:"DoD - Releases",agency:"DoD",description:"defense",rssUrl:"https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=9&Site=945&max=10",website:"https://www.defense.gov",department:"",category:"Defense & Security",subCategory:"defense",contentType:"defense",updateFrequency:"",status:"working" as const,tags:["defense"]},
  {id:"feed-125",name:"DoD - Transcripts",shortName:"DoD - Transcripts",agency:"DoD",description:"defense",rssUrl:"https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?max=10&ContentType=3&Site=945",website:"https://www.defense.gov",department:"",category:"Defense & Security",subCategory:"defense",contentType:"defense",updateFrequency:"",status:"working" as const,tags:["defense"]},
  {id:"feed-126",name:"DoD News Articles",shortName:"DoD News Articles",agency:"Department of Defense (DoD)",description:"Operational developments, defense policy initiatives, and military leadership decisions.",rssUrl:"https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=945",website:"https://www.defense.gov",department:"",category:"Defense & Security",subCategory:"Defense & Security",contentType:"Operational developments, defense policy initiatives, and military leadership decisions.",updateFrequency:"",status:"working" as const,tags:["defense & security"]},
  {id:"feed-169",name:"State Dept - Travel Advisories",shortName:"State Dept - Travel Advisories",agency:"State Dept",description:"diplomacy",rssUrl:"https://travel.state.gov/_res/rss/TAsTWs.xml",website:"https://travel.state.gov",department:"",category:"Diplomacy & Foreign Affairs",subCategory:"diplomacy",contentType:"diplomacy",updateFrequency:"",status:"working" as const,tags:["diplomacy"]},
  {id:"feed-235",name:"CFPB Press Releases",shortName:"CFPB Press Releases",agency:"Consumer Financial Protection Bureau (CFPB)",description:"Administrative actions, consumer finance protection directives, and banking fine summaries.",rssUrl:"https://www.consumerfinance.gov/about-us/newsroom/feed/",website:"https://www.consumerfinance.gov",department:"",category:"Finance & Economy",subCategory:"Finance & Economy",contentType:"Administrative actions, consumer finance protection directives, and banking fine summaries.",updateFrequency:"",status:"working" as const,tags:["finance & economy"]},
  {id:"feed-243",name:"Federal Reserve - All Press Releases",shortName:"Reserve - All Press Releases",agency:"Federal Reserve",description:"finance",rssUrl:"https://www.federalreserve.gov/feeds/press_all.xml",website:"https://www.federalreserve.gov",department:"",category:"Finance & Economy",subCategory:"finance",contentType:"finance",updateFrequency:"",status:"working" as const,tags:["finance"]},
  {id:"feed-258",name:"Federal Reserve - Speeches & Testimony",shortName:"Reserve - Speeches & Testimony",agency:"Federal Reserve",description:"finance",rssUrl:"https://www.federalreserve.gov/feeds/speeches.xml",website:"https://www.federalreserve.gov",department:"",category:"Finance & Economy",subCategory:"finance",contentType:"finance",updateFrequency:"",status:"working" as const,tags:["finance"]},
  {id:"feed-262",name:"SEC Speeches and Statements",shortName:"SEC Speeches and Statements",agency:"Securities and Exchange Commission (SEC)",description:"Official commentary, guidance statements, and public positions of SEC Commissioners.",rssUrl:"https://www.sec.gov/news/speeches.rss",website:"https://www.sec.gov",department:"",category:"Finance & Economy",subCategory:"Finance & Economy",contentType:"Official commentary, guidance statements, and public positions of SEC Commissioners.",updateFrequency:"",status:"working" as const,tags:["finance & economy"]},
  {id:"feed-275",name:"Breaking News",shortName:"Breaking News",agency:"NASA",description:"Breaking News",rssUrl:"https://www.nasa.gov/rss/dyn/breaking_news.rss",website:"https://www.nasa.gov",department:"",category:"General",subCategory:"breaking-news",contentType:"Breaking News",updateFrequency:"",status:"working" as const,tags:["breaking-news"]},
  {id:"feed-283",name:"GovInfo - Bulk Bills",shortName:"GovInfo - Bulk Bills",agency:"GovInfo",description:"bulk",rssUrl:"https://www.govinfo.gov/rss/bills-bulkdata.xml",website:"https://www.govinfo.gov",department:"",category:"General",subCategory:"bulk",contentType:"bulk",updateFrequency:"",status:"working" as const,tags:["bulk"]},
  {id:"feed-285",name:"GovInfo - Bulk CFR",shortName:"GovInfo - Bulk CFR",agency:"GovInfo",description:"bulk",rssUrl:"https://www.govinfo.gov/rss/cfr-bulkdata.xml",website:"https://www.govinfo.gov",department:"",category:"General",subCategory:"bulk",contentType:"bulk",updateFrequency:"",status:"working" as const,tags:["bulk"]},
  {id:"feed-289",name:"GovInfo - Bulk Federal Register",shortName:"GovInfo - Bulk Federal Register",agency:"GovInfo",description:"bulk",rssUrl:"https://www.govinfo.gov/rss/fr-bulkdata.xml",website:"https://www.govinfo.gov",department:"",category:"General",subCategory:"bulk",contentType:"bulk",updateFrequency:"",status:"working" as const,tags:["bulk"]},
  {id:"feed-292",name:"GovInfo - Bulk Public Laws",shortName:"GovInfo - Bulk Public Laws",agency:"GovInfo",description:"bulk",rssUrl:"https://www.govinfo.gov/rss/plaw-bulkdata.xml",website:"https://www.govinfo.gov",department:"",category:"General",subCategory:"bulk",contentType:"bulk",updateFrequency:"",status:"working" as const,tags:["bulk"]},
  {id:"feed-303",name:"Space Weather Alerts",shortName:"Space Weather Alerts",agency:"NOAA Space Weather Prediction Center",description:"Space Weather",rssUrl:"https://www.swpc.noaa.gov/rss.xml",website:"https://www.swpc.noaa.gov",department:"",category:"General",subCategory:"space-weather",contentType:"Space Weather",updateFrequency:"",status:"working" as const,tags:["space-weather"]},
  {id:"feed-317",name:"Library of Congress - Blog",shortName:"Library of Congress - Blog",agency:"Library of Congress",description:"culture",rssUrl:"https://blogs.loc.gov/loc/feed/",website:"https://blogs.loc.gov",department:"",category:"Grants & Arts",subCategory:"culture",contentType:"culture",updateFrequency:"",status:"working" as const,tags:["culture"]},
  {id:"feed-339",name:"Morbidity and Mortality Weekly Report",shortName:"Morbidity and Mortality Weekly Report",agency:"CDC MMWR",description:"Epidemiological Data",rssUrl:"https://www.cdc.gov/mmwr/rss/mmwr.xml",website:"https://www.cdc.gov",department:"",category:"Health & Science",subCategory:"epidemiological-data",contentType:"Epidemiological Data",updateFrequency:"",status:"working" as const,tags:["epidemiological-data"]},
  {id:"feed-353",name:"NSF News",shortName:"NSF News",agency:"National Science Foundation",description:"Science Research",rssUrl:"https://www.nsf.gov/rss/rss_www_news.xml",website:"https://www.nsf.gov",department:"",category:"Health & Science",subCategory:"science-research",contentType:"Science Research",updateFrequency:"",status:"working" as const,tags:["science-research"]},
  {id:"feed-383",name:"OSHA - Federal Register",shortName:"OSHA - Federal Register",agency:"OSHA",description:"labor",rssUrl:"https://www.osha.gov/laws-regs/federalregisters.xml",website:"https://www.osha.gov",department:"",category:"Labor & Employment",subCategory:"labor",contentType:"labor",updateFrequency:"",status:"working" as const,tags:["labor"]},
  {id:"feed-384",name:"OSHA - News Releases",shortName:"OSHA - News Releases",agency:"OSHA",description:"labor",rssUrl:"https://www.osha.gov/news/newsreleases.xml",website:"https://www.osha.gov",department:"",category:"Labor & Employment",subCategory:"labor",contentType:"labor",updateFrequency:"",status:"working" as const,tags:["labor"]},
  {id:"feed-388",name:"OSHA News",shortName:"OSHA News",agency:"Occupational Safety and Health Administration",description:"Workplace Safety",rssUrl:"https://www.osha.gov/rss.xml",website:"https://www.osha.gov",department:"",category:"Labor & Employment",subCategory:"workplace-safety",contentType:"Workplace Safety",updateFrequency:"",status:"working" as const,tags:["workplace-safety"]},
  {id:"feed-403",name:"FTC - Competition",shortName:"FTC - Competition",agency:"FTC",description:"enforcement",rssUrl:"https://www.ftc.gov/feeds/press-release-competition.xml",website:"https://www.ftc.gov",department:"",category:"Oversight & Audits",subCategory:"enforcement",contentType:"enforcement",updateFrequency:"",status:"working" as const,tags:["enforcement"]},
  {id:"feed-404",name:"FTC - Consumer Protection",shortName:"FTC - Consumer Protection",agency:"FTC",description:"enforcement",rssUrl:"https://www.ftc.gov/feeds/press-release-consumer-protection.xml",website:"https://www.ftc.gov",department:"",category:"Oversight & Audits",subCategory:"enforcement",contentType:"enforcement",updateFrequency:"",status:"working" as const,tags:["enforcement"]},
  {id:"feed-407",name:"GAO - Auditing",shortName:"GAO - Auditing",agency:"GAO",description:"audit",rssUrl:"https://www.gao.gov/rss/topic/Auditing_and_Financial_Management",website:"https://www.gao.gov",department:"",category:"Oversight & Audits",subCategory:"audit",contentType:"audit",updateFrequency:"",status:"working" as const,tags:["audit"]},
  {id:"feed-408",name:"GAO - Blog",shortName:"GAO - Blog",agency:"GAO",description:"audit",rssUrl:"https://www.gao.gov/blog/feed",website:"https://www.gao.gov",department:"",category:"Oversight & Audits",subCategory:"audit",contentType:"audit",updateFrequency:"",status:"working" as const,tags:["audit"]},
  {id:"feed-410",name:"GAO - Homeland Security",shortName:"GAO - Homeland Security",agency:"GAO",description:"audit",rssUrl:"https://www.gao.gov/rss/topic/Homeland_Security",website:"https://www.gao.gov",department:"",category:"Oversight & Audits",subCategory:"audit",contentType:"audit",updateFrequency:"",status:"working" as const,tags:["audit"]},
  {id:"feed-411",name:"GAO - Info Security",shortName:"GAO - Info Security",agency:"GAO",description:"audit",rssUrl:"https://www.gao.gov/rss/topic/Information_Security",website:"https://www.gao.gov",department:"",category:"Oversight & Audits",subCategory:"audit",contentType:"audit",updateFrequency:"",status:"working" as const,tags:["audit"]},
  {id:"feed-413",name:"GAO - Legal Products",shortName:"GAO - Legal Products",agency:"GAO",description:"audit",rssUrl:"https://www.gao.gov/rss/reportslegal.xml",website:"https://www.gao.gov",department:"",category:"Oversight & Audits",subCategory:"audit",contentType:"audit",updateFrequency:"",status:"working" as const,tags:["audit"]},
  {id:"feed-414",name:"GAO - Major Rules",shortName:"GAO - Major Rules",agency:"GAO",description:"audit",rssUrl:"https://www.gao.gov/rss/reports_majrule.xml",website:"https://www.gao.gov",department:"",category:"Oversight & Audits",subCategory:"audit",contentType:"audit",updateFrequency:"",status:"working" as const,tags:["audit"]},
  {id:"feed-415",name:"GAO - Podcast",shortName:"GAO - Podcast",agency:"GAO",description:"audit",rssUrl:"https://www.gao.gov/podcast/watchdog.xml",website:"https://www.gao.gov",department:"",category:"Oversight & Audits",subCategory:"audit",contentType:"audit",updateFrequency:"",status:"working" as const,tags:["audit"]},
  {id:"feed-417",name:"GAO - Reports",shortName:"GAO - Reports",agency:"GAO",description:"audit",rssUrl:"https://www.gao.gov/rss/reports.xml",website:"https://www.gao.gov",department:"",category:"Oversight & Audits",subCategory:"audit",contentType:"audit",updateFrequency:"",status:"working" as const,tags:["audit"]},
  {id:"feed-418",name:"GAO - Reports (Brief)",shortName:"GAO - Reports (Brief)",agency:"GAO",description:"audit",rssUrl:"https://www.gao.gov/rss/reports_450.xml",website:"https://www.gao.gov",department:"",category:"Oversight & Audits",subCategory:"audit",contentType:"audit",updateFrequency:"",status:"working" as const,tags:["audit"]},
  {id:"feed-434",name:"SEC - Press Releases",shortName:"SEC - Press Releases",agency:"SEC",description:"enforcement",rssUrl:"https://www.sec.gov/news/pressreleases.rss",website:"https://www.sec.gov",department:"",category:"Oversight & Audits",subCategory:"enforcement",contentType:"enforcement",updateFrequency:"",status:"working" as const,tags:["enforcement"]},
  {id:"feed-435",name:"SEC - Speeches",shortName:"SEC - Speeches",agency:"SEC",description:"enforcement",rssUrl:"https://www.sec.gov/news/speeches-statements.rss",website:"https://www.sec.gov",department:"",category:"Oversight & Audits",subCategory:"enforcement",contentType:"enforcement",updateFrequency:"",status:"working" as const,tags:["enforcement"]},
  {id:"feed-436",name:"SEC - Statements",shortName:"SEC - Statements",agency:"SEC",description:"enforcement",rssUrl:"https://www.sec.gov/news/statements.rss",website:"https://www.sec.gov",department:"",category:"Oversight & Audits",subCategory:"enforcement",contentType:"enforcement",updateFrequency:"",status:"working" as const,tags:["enforcement"]},
  {id:"feed-439",name:"USAID OIG Reports",shortName:"USAID OIG Reports",agency:"Agency for International Development Office of Inspector General (USAID OIG)",description:"Reviews of international humanitarian aid distributions, development funding, and disaster response.",rssUrl:"https://oig.usaid.gov/rss.xml",website:"https://oig.usaid.gov",department:"",category:"Oversight & Audits",subCategory:"Oversight & Audits",contentType:"Reviews of international humanitarian aid distributions, development funding, and disaster response.",updateFrequency:"",status:"working" as const,tags:["oversight & audits"]},
  {id:"feed-446",name:"GovInfo - CFR",shortName:"GovInfo - CFR",agency:"GovInfo",description:"rulemaking",rssUrl:"https://www.govinfo.gov/rss/cfr.xml",website:"https://www.govinfo.gov",department:"",category:"Rulemaking & Regulations",subCategory:"rulemaking",contentType:"rulemaking",updateFrequency:"",status:"working" as const,tags:["rulemaking"]},
  {id:"feed-447",name:"GovInfo - Federal Register",shortName:"GovInfo - Federal Register",agency:"GovInfo",description:"rulemaking",rssUrl:"https://www.govinfo.gov/rss/fr.xml",website:"https://www.govinfo.gov",department:"",category:"Rulemaking & Regulations",subCategory:"rulemaking",contentType:"rulemaking",updateFrequency:"",status:"working" as const,tags:["rulemaking"]},
  {id:"feed-475",name:"CISA Cyber Advisories",shortName:"CISA Cyber Advisories",agency:"Cybersecurity and Infrastructure Security Agency",description:"Real-time security alerts on critical infrastructure system vulnerabilities and exploit mitigation guides.",rssUrl:"https://www.cisa.gov/cybersecurity-advisories/all.xml",website:"https://www.cisa.gov",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"Technology, Cybersecurity, & Space",contentType:"Real-time security alerts on critical infrastructure system vulnerabilities and exploit mitigation guides.",updateFrequency:"",status:"working" as const,tags:["technology, cybersecurity, & space"]},
  {id:"feed-480",name:"NASA Image of the Day",shortName:"NASA Image of the Day",agency:"National Aeronautics and Space Administration",description:"Astronomical observations and planetary exploration telemetry.",rssUrl:"https://www.nasa.gov/rss/dyn/image_of_the_day.rss",website:"https://www.nasa.gov",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"Technology, Cybersecurity, & Space",contentType:"Astronomical observations and planetary exploration telemetry.",updateFrequency:"",status:"working" as const,tags:["technology, cybersecurity, & space"]},
  {id:"feed-504",name:"VA News Press Releases",shortName:"VA News Press Releases",agency:"Department of Veterans Affairs (VA)",description:"Administrative changes, benefit updates, and clinical healthcare expansions for veterans.",rssUrl:"https://news.va.gov/feed/",website:"https://news.va.gov",department:"",category:"Veterans Affairs, Healthcare, & Benefits",subCategory:"Veterans Affairs, Healthcare, & Benefits",contentType:"Administrative changes, benefit updates, and clinical healthcare expansions for veterans.",updateFrequency:"",status:"working" as const,tags:["veterans affairs, healthcare, & benefits"]},
  {id:"feed-517",name:"Department of the Interior - Bureau of Land Management",shortName:"Department of the Interior - Bureau of Land Manage",agency:"Department of the Interior - Bureau of Land Management",description:"Department of the Interior - Bureau of Land Management",rssUrl:"https://www.blm.gov/press-release/national-office/rss",website:"https://www.blm.gov/info/RSS-feeds",department:"",category:"Environment & Energy",subCategory:"Environment & Energy",contentType:"Department of the Interior - Bureau of Land Management",updateFrequency:"",status:"working" as const,tags:["environment & energy"]},
  {id:"feed-530",name:"DOD Network Information Center / Defense Travel Management Office",shortName:"DOD Network Information Center / Defense Travel Ma",agency:"DOD Network Information Center / Defense Travel Management Office",description:"DOD Network Information Center / Defense Travel Management Office",rssUrl:"https://www.travel.dod.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=1311&max=20",website:"https://www.travel.dod.mil",department:"",category:"Defense & Security",subCategory:"Defense & Security",contentType:"DOD Network Information Center / Defense Travel Management Office",updateFrequency:"",status:"working" as const,tags:["defense & security"]},
  {id:"feed-531",name:"DOD Network Information Center / Defense Visual Information Directorate",shortName:"DOD Network Information Center / Defense Visual In",agency:"DOD Network Information Center / Defense Visual Information Directorate",description:"DOD Network Information Center / Defense Visual Information Directorate",rssUrl:"https://www.dvidshub.net/rss/news",website:"https://www.dvidshub.net",department:"",category:"Defense & Security",subCategory:"Defense & Security",contentType:"DOD Network Information Center / Defense Visual Information Directorate",updateFrequency:"",status:"working" as const,tags:["defense & security"]},
  {id:"feed-551",name:"Federal Trade Commission",shortName:"Federal Trade Commission",agency:"Federal Trade Commission",description:"Federal Trade Commission",rssUrl:"https://www.ftc.gov/feeds/press-release.xml",website:"https://www.ftc.gov/news-events/stay-connected/ftc-rss-feeds",department:"",category:"Commerce & Trade",subCategory:"Commerce & Trade",contentType:"Federal Trade Commission",updateFrequency:"",status:"working" as const,tags:["commerce & trade"]},
  {id:"feed-553",name:"Fermi National Accelerator Laboratory (Fermilab)",shortName:"Fermi National Accelerator Laboratory (Fermilab)",agency:"Fermi National Accelerator Laboratory (Fermilab)",description:"Fermi National Accelerator Laboratory (Fermilab)",rssUrl:"http://news.fnal.gov/rss-news",website:"https://news.fnal.gov/",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"Technology, Cybersecurity, & Space",contentType:"Fermi National Accelerator Laboratory (Fermilab)",updateFrequency:"",status:"working" as const,tags:["technology, cybersecurity, & space"]},
  {id:"feed-555",name:"Headquarters USAISC / Headquarters, Department of the Army",shortName:"Headquarters USAISC / Headquarters, Department of ",agency:"Headquarters USAISC / Headquarters, Department of the Army",description:"Headquarters USAISC / Headquarters, Department of the Army",rssUrl:"https://www.army.mil/rss/static/1.xml",website:"https://www.army.mil",department:"",category:"Defense & Security",subCategory:"Defense & Security",contentType:"Headquarters USAISC / Headquarters, Department of the Army",updateFrequency:"",status:"working" as const,tags:["defense & security"]},
  {id:"feed-556",name:"Headquarters USAISC / National Guard",shortName:"Headquarters USAISC / National Guard",agency:"Headquarters USAISC / National Guard",description:"Headquarters USAISC / National Guard",rssUrl:"https://www.nationalguard.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=688&Category=11199&max=20",website:"https://www.nationalguard.mil/News/RSS-Feeds/",department:"",category:"Defense & Security",subCategory:"Defense & Security",contentType:"Headquarters USAISC / National Guard",updateFrequency:"",status:"working" as const,tags:["defense & security"]},
  {id:"feed-560",name:"Headquarters USAISC / U.S. Army Corps of Engineers - Engineering and Support Center - Huntsville",shortName:"Headquarters USAISC / U.S. Army Corps of Engineers",agency:"Headquarters USAISC / U.S. Army Corps of Engineers - Engineering and Support Center - Huntsville",description:"Headquarters USAISC / U.S. Army Corps of Engineers - Engineering and Support Center - Huntsville",rssUrl:"https://www.hnc.usace.army.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=443&isdashboardselected=0&max=20&Category=21408",website:"https://www.hnc.usace.army.mil/Contact/RSS/",department:"",category:"Defense & Security",subCategory:"Defense & Security",contentType:"Headquarters USAISC / U.S. Army Corps of Engineers - Engineering and Support Center - Huntsville",updateFrequency:"",status:"working" as const,tags:["defense & security"]},
  {id:"feed-570",name:"Headquarters USAISC / U.S. Army Corps of Engineers - St. Paul District",shortName:"Headquarters USAISC / U.S. Army Corps of Engineers",agency:"Headquarters USAISC / U.S. Army Corps of Engineers - St. Paul District",description:"Headquarters USAISC / U.S. Army Corps of Engineers - St. Paul District",rssUrl:"https://www.mvp.usace.army.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=9&Site=465&isdashboardselected=0&max=20&Category=20858",website:"https://www.mvp.usace.army.mil/Contact/RSS/",department:"",category:"Defense & Security",subCategory:"Defense & Security",contentType:"Headquarters USAISC / U.S. Army Corps of Engineers - St. Paul District",updateFrequency:"",status:"working" as const,tags:["defense & security"]},
  {id:"feed-576",name:"International Boundary and Water Commission",shortName:"International Boundary and Water Commission",agency:"International Boundary and Water Commission",description:"International Boundary and Water Commission",rssUrl:"https://www.ibwc.gov/feed/",website:"https://www.ibwc.gov/press-releases/",department:"",category:"Diplomacy & Foreign Affairs",subCategory:"Diplomacy & Foreign Affairs",contentType:"International Boundary and Water Commission",updateFrequency:"",status:"working" as const,tags:["diplomacy & foreign affairs"]},
  {id:"feed-584",name:"National Aeronautics and Space Administration",shortName:"National Aeronautics and Space Administration",agency:"National Aeronautics and Space Administration",description:"National Aeronautics and Space Administration",rssUrl:"https://www.nasa.gov/news-release/feed/",website:"https://www.nasa.gov/rss-feeds/",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"Technology, Cybersecurity, & Space",contentType:"National Aeronautics and Space Administration",updateFrequency:"",status:"working" as const,tags:["technology, cybersecurity, & space"]},
  {id:"feed-606",name:"Sandia National Laboratories",shortName:"Sandia National Laboratories",agency:"Sandia National Laboratories",description:"Sandia National Laboratories",rssUrl:"https://newsreleases.sandia.gov/feed/",website:"https://newsreleases.sandia.gov/",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"Technology, Cybersecurity, & Space",contentType:"Sandia National Laboratories",updateFrequency:"",status:"working" as const,tags:["technology, cybersecurity, & space"]},
  {id:"feed-608",name:"United States Centers for Disease Control",shortName:"United States Centers for Disease Control",agency:"United States Centers for Disease Control",description:"United States Centers for Disease Control",rssUrl:"https://tools.cdc.gov/api/v2/resources/media/132608.rss",website:"https://tools.cdc.gov/",department:"",category:"Health & Science",subCategory:"Health & Science",contentType:"United States Centers for Disease Control",updateFrequency:"",status:"working" as const,tags:["health & science"]},
  {id:"feed-616",name:"U.S. House of Representatives",shortName:"U.S. House of Representatives",agency:"U.S. House of Representatives",description:"U.S. House of Representatives",rssUrl:"https://clerk.house.gov/Home/Feed",website:"https://clerk.house.gov/FloorSummary",department:"",category:"Congress & Legislation",subCategory:"Congress & Legislation",contentType:"U.S. House of Representatives",updateFrequency:"",status:"working" as const,tags:["congress & legislation"]},

  // ─── Government Security Feeds ─────────────────────────────────
  {id:"feed-700",name:"CISA Blog",shortName:"CISA Blog",agency:"Cybersecurity and Infrastructure Security Agency (CISA)",description:"CISA blog posts on cybersecurity initiatives, partnerships, and public awareness campaigns.",rssUrl:"https://www.cisa.gov/blog.xml",website:"https://www.cisa.gov/news-events/blog",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"cybersecurity",contentType:"Blog posts on cybersecurity initiatives and awareness.",updateFrequency:"",status:"working" as const,tags:["cybersecurity","cisa","alerts"]},
  {id:"feed-701",name:"CISA News",shortName:"CISA News",agency:"Cybersecurity and Infrastructure Security Agency (CISA)",description:"Official CISA news releases, advisories, and guidance on vulnerabilities and threats.",rssUrl:"https://www.cisa.gov/news.xml",website:"https://www.cisa.gov/news-events/news",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"cybersecurity",contentType:"News releases and advisories on vulnerabilities and threats.",updateFrequency:"",status:"working" as const,tags:["cybersecurity","cisa","news"]},
  {id:"feed-702",name:"CISA Alerts",shortName:"CISA Alerts",agency:"Cybersecurity and Infrastructure Security Agency (CISA)",description:"US-CERT/CISA technical alerts covering active threats, vulnerabilities, and mitigations.",rssUrl:"https://www.us-cert.gov/ncas/alerts.xml",website:"https://www.cisa.gov/uscert/ncas/alerts",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"cybersecurity",contentType:"Technical alerts on active threats and mitigations.",updateFrequency:"",status:"working" as const,tags:["cybersecurity","cisa","alerts","threats"]},
  {id:"feed-703",name:"CISA Current Activity",shortName:"CISA Current Activity",agency:"Cybersecurity and Infrastructure Security Agency (CISA)",description:"US-CERT/CISA current activity feed highlighting recent cybersecurity events and emerging threats.",rssUrl:"https://us-cert.cisa.gov/ncas/current-activity.xml",website:"https://www.cisa.gov/uscert/ncas/current-activity",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"cybersecurity",contentType:"Current activity on cybersecurity events and emerging threats.",updateFrequency:"",status:"working" as const,tags:["cybersecurity","cisa","threats","activity"]},
  {id:"feed-704",name:"CISA Analysis Reports",shortName:"CISA Analysis Reports",agency:"Cybersecurity and Infrastructure Security Agency (CISA)",description:"US-CERT/CISA analysis reports providing in-depth technical analysis of threats and vulnerabilities.",rssUrl:"https://us-cert.cisa.gov/ncas/analysis-reports.xml",website:"https://www.cisa.gov/uscert/ncas/analysis-reports",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"cybersecurity",contentType:"In-depth technical analysis of threats and vulnerabilities.",updateFrequency:"",status:"working" as const,tags:["cybersecurity","cisa","analysis","reports"]},
  {id:"feed-705",name:"CISA ICS Advisories",shortName:"CISA ICS Advisories",agency:"Cybersecurity and Infrastructure Security Agency (CISA)",description:"CISA Industrial Control Systems advisories for critical infrastructure vulnerabilities.",rssUrl:"https://us-cert.cisa.gov/ics/advisories/advisories.xml",website:"https://www.cisa.gov/uscert/ics/advisories",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"cybersecurity",contentType:"Industrial Control Systems advisories for critical infrastructure.",updateFrequency:"",status:"working" as const,tags:["cybersecurity","cisa","ics","advisories","critical infrastructure"]},
  {id:"feed-706",name:"CERT Vulnerability Notes",shortName:"CERT Vulnerability Notes",agency:"CERT Coordination Center",description:"CERT/CC vulnerability notes with summaries, technical details, remediation, and affected vendors.",rssUrl:"https://www.kb.cert.org/vulfeed",website:"https://www.kb.cert.org/vuls",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"cybersecurity",contentType:"Vulnerability notes with technical details and remediation.",updateFrequency:"",status:"working" as const,tags:["cybersecurity","cert","vulnerabilities","cve"]},
  {id:"feed-707",name:"NIST Cybersecurity Insights",shortName:"NIST Cybersecurity Insights",agency:"National Institute of Standards and Technology (NIST)",description:"NIST cybersecurity blog posts on standards, frameworks, and best practices.",rssUrl:"https://www.nist.gov/blogs/cybersecurity-insights/rss.xml",website:"https://www.nist.gov/blogs/cybersecurity-insights",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"cybersecurity",contentType:"Blog posts on cybersecurity standards and best practices.",updateFrequency:"",status:"working" as const,tags:["cybersecurity","nist","standards"]},
  {id:"feed-708",name:"NIST Cybersecurity News",shortName:"NIST Cybersecurity News",agency:"National Institute of Standards and Technology (NIST)",description:"NIST cybersecurity news and events feed.",rssUrl:"https://www.nist.gov/news-events/cybersecurity/rss.xml",website:"https://www.nist.gov/news-events/cybersecurity",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"cybersecurity",contentType:"Cybersecurity news and events.",updateFrequency:"",status:"working" as const,tags:["cybersecurity","nist","news"]},
  {id:"feed-709",name:"GovInfoSecurity",shortName:"GovInfoSecurity",agency:"GovInfoSecurity.com",description:"Government information security news, regulations, blogs and education.",rssUrl:"https://www.govinfosecurity.com/rss-feeds",website:"https://www.govinfosecurity.com",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"cybersecurity",contentType:"Government information security news and regulations.",updateFrequency:"",status:"working" as const,tags:["cybersecurity","government","news","privacy"]},
  {id:"feed-710",name:"SANS Internet Storm Center",shortName:"SANS ISC",agency:"SANS Institute",description:"SANS Internet Storm Center daily threat briefs and handler diaries.",rssUrl:"https://isc.sans.edu/rssfeed_full.xml",website:"https://isc.sans.edu",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"cybersecurity",contentType:"Daily threat briefs and handler diaries.",updateFrequency:"",status:"working" as const,tags:["cybersecurity","sans","threats","diaries"]},
  {id:"feed-711",name:"MSRC Security Update Guide",shortName:"MSRC Updates",agency:"Microsoft Security Response Center",description:"Microsoft Security Response Center security update guide for Microsoft products.",rssUrl:"https://api.msrc.microsoft.com/update-guide/rss",website:"https://msrc.microsoft.com/update-guide",department:"",category:"Technology, Cybersecurity, & Space",subCategory:"cybersecurity",contentType:"Security update guide for Microsoft products.",updateFrequency:"",status:"working" as const,tags:["cybersecurity","microsoft","updates","patches"]},
];

export const feedStats = {
  total: 90,
  byCategory: {
    "Commerce & Trade": 2,
    "Congress & Legislation": 8,
    "Courts & Judiciary": 13,
    "Defense & Security": 12,
    "Diplomacy & Foreign Affairs": 2,
    "Finance & Economy": 4,
    "General": 6,
    "Grants & Arts": 1,
    "Health & Science": 3,
    "Labor & Employment": 3,
    "Oversight & Audits": 15,
    "Rulemaking & Regulations": 2,
    "Technology, Cybersecurity, & Space": 17,
    "Veterans Affairs, Healthcare, & Benefits": 1,
    "Environment & Energy": 1,
  }
};

export const categoryList: string[] = [
  "Commerce & Trade",
  "Congress & Legislation",
  "Courts & Judiciary",
  "Defense & Security",
  "Diplomacy & Foreign Affairs",
  "Finance & Economy",
  "General",
  "Grants & Arts",
  "Health & Science",
  "Labor & Employment",
  "Oversight & Audits",
  "Rulemaking & Regulations",
  "Technology, Cybersecurity, & Space",
  "Veterans Affairs, Healthcare, & Benefits",
  "Environment & Energy",
];

export const getFeedsByCategory = (category: string): Feed[] => feeds.filter(f => f.category === category);
export const getFeedById = (id: string): Feed | undefined => feeds.find(f => f.id === id);
export const searchFeeds = (query: string): Feed[] => {
  const q = query.toLowerCase();
  return feeds.filter(f => f.name.toLowerCase().includes(q) || f.agency.toLowerCase().includes(q) || f.category.toLowerCase().includes(q) || f.tags.some(t => t.toLowerCase().includes(q)));
};
